export const categories = [
	{
		id: 1,
		name: "Pizza",
		image: require("../assets/pizza1.jpg"),
	},
	{
		id: 2,
		name: "Burger",
		image: require("../assets/pizza1.jpg"),
	},
	{
		id: 3,
		name: "Italian",
		image: require("../assets/pizza1.jpg"),
	},
	{
		id: 4,
		name: "Chinese",
		image: require("../assets/pizza1.jpg"),
	},
	{
		id: 5,
		name: "Noodles",
		image: require("../assets/pizza1.jpg"),
	},
	{
		id: 6,
		name: "Sweets",
		image: require("../assets/pizza1.jpg"),
	},
];

export const featured = {
	id: 1,
	title: "Hot and Spicy",
	description: "soft and tender fried chicken",
	restaurants: [
		{
			id: 1,
			name: "Papa Johns",
			image: require("../assets/pizza2.jpg"),
			description: "Hot and spicy pizzas",
			lng: 106.67042294203874,
			lat: 10.871072763032917,
			address: "434 second street",
			stars: 4,
			reviews: "4.4k",
			category: "Fast Food",
			dishes: [
				{
					id: 1,
					name: "pizza",
					description: "cheezy garlic pizza",
					price: 10,
					image: require("../assets/pizza1.jpg"),
				},
				{
					id: 2,
					name: "pizza",
					description: "cheezy garlic pizza",
					price: 10,
					image: require("../assets/pizza1.jpg"),
				},
				{
					id: 3,
					name: "pizza",
					description: "cheezy garlic pizza",
					price: 10,
					image: require("../assets/pizza1.jpg"),
				},
				{
					id: 4,
					name: "pizza",
					description: "cheezy garlic pizza",
					price: 10,
					image: require("../assets/pizza1.jpg"),
				},
				{
					id: 5,
					name: "pizza",
					description: "cheezy garlic pizza",
					price: 10,
					image: require("../assets/pizza1.jpg"),
				},
				{
					id: 6,
					name: "pizza",
					description: "cheezy garlic pizza",
					price: 10,
					image: require("../assets/pizza1.jpg"),
				},
				{
					id: 6,
					name: "pizza",
					description: "cheezy garlic pizza",
					price: 10,
					image: require("../assets/pizza1.jpg"),
				},
				{
					id: 6,
					name: "pizza",
					description: "cheezy garlic pizza",
					price: 10,
					image: require("../assets/pizza1.jpg"),
				},
				{
					id: 6,
					name: "pizza",
					description: "cheezy garlic pizza",
					price: 10,
					image: require("../assets/pizza1.jpg"),
				},
				{
					id: 6,
					name: "pizza",
					description: "cheezy garlic pizza",
					price: 10,
					image: require("../assets/pizza1.jpg"),
				},
			],
		},
		{
			id: 2,
			name: "Papa Johns",
			image: require("../assets/pizza2.jpg"),
			description: "Hot and spicy pizzas",
			lng: -85.5324269,
			lat: 38.2145602,
			address: "434 second street",
			stars: 4,
			reviews: "4.4k",
			category: "Fast Food",
			dishes: [
				{
					id: 1,
					name: "pizza",
					description: "cheezy garlic pizza",
					price: 10,
					image: require("../assets/pizza1.jpg"),
				},
				{
					id: 2,
					name: "pizza",
					description: "cheezy garlic pizza",
					price: 10,
					image: require("../assets/pizza1.jpg"),
				},
				{
					id: 3,
					name: "pizza",
					description: "cheezy garlic pizza",
					price: 10,
					image: require("../assets/pizza1.jpg"),
				},
			],
		},
		{
			id: 3,
			name: "Papa Johns",
			image: require("../assets/pizza2.jpg"),
			description: "Hot and spicy pizzas",
			lng: -85.5324269,
			lat: 38.2145602,
			address: "434 second street",
			stars: 4,
			reviews: "4.4k",
			category: "Fast Food",
			dishes: [
				{
					id: 1,
					name: "pizza",
					description: "cheezy garlic pizza",
					price: 10,
					image: require("../assets/pizza1.jpg"),
				},
				{
					id: 2,
					name: "pizza",
					description: "cheezy garlic pizza",
					price: 10,
					image: require("../assets/pizza1.jpg"),
				},
				{
					id: 3,
					name: "pizza",
					description: "cheezy garlic pizza",
					price: 10,
					image: require("../assets/pizza1.jpg"),
				},
			],
		},
	],
};
